server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ali_blog_db
spring.datasource.username=postgres
spring.datasource.password=Hasan@3135

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=my-super-secret-key-for-blog-app-authentication-123456
jwt.expiration-ms=86400000

admin.email=admin@aliblog.com
admin.password=Admin123!
